name: 'CI'
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        label: [actuated, actuated-aarch64, ubuntu-latest]
    runs-on: ${{ matrix.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
      - name: Build faasd 🔧
        run: |
          nix build -L .#packages.aarch64-linux.faasd
      - name: Build containerd 🔧
        run: |
          nix build -L .#packages.aarch64-linux.faasd-containerd
      - name: Build cni-plugin 🔧
        run: |
          nix build -L .#packages.aarch64-linux.faasd-cni-plugins
